/*
	Supabase project info.
	Prefer using Vite env vars for production:
		VITE_SUPABASE_PROJECT_ID
		VITE_SUPABASE_ANON_KEY

	This file falls back to the autogenerated values for local/dev convenience.
*/

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "tpxgfjevorhdtwkesvcb";
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRweGdmamV2b3JoZHR3a2VzdmNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyNDE3MjIsImV4cCI6MjA4NjgxNzcyMn0.K50o48WDbgmWvASexy3SCX2XfWiP_WQtCAkou49aFO8";

// Optional: full Supabase URL (useful for local `supabase start`)
export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || `https://${projectId}.supabase.co`;